apiVersion: v1
kind: ConfigMap
metadata:
  name: vmagent-config
  namespace: monitoring
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['192.168.49.2:9100']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmagent
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmagent
  template:
    metadata:
      labels:
        app: vmagent
    spec:
      containers:
        - name: vmagent
          image: victoriametrics/vmagent:v1.84.0
          args:
            - "--remoteWrite.url=http://vmsingle-vm-single:8428/api/v1/write"
            - "--promscrape.config=/etc/vmagent/prometheus.yml"
          volumeMounts:
            - name: config
              mountPath: /etc/vmagent
      volumes:
        - name: config
          configMap:
            name: vmagent-config
scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: ["192.168.49.2:9100"]

  - job_name: "kube-state-metrics"
    static_configs:
      - targets: ["ksm-kube-state-metrics.monitoring.svc.cluster.local:8080"]
