apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vmagent.fullname" . }}-config
  labels:
    app: {{ include "vmagent.name" . }}
data:
  prometheus.yml: |
    scrape_configs:
{{- range .Values.scrapeConfigs }}
      - job_name: '{{ .job_name }}'
        static_configs:
{{- range .targets }}
          - targets: ['{{ . }}']
{{- end }}
{{- end }}
