apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring.fullname" . }}
spec:
  selector:
    app: {{ include "monitoring.name" . }}
  ports:
    - protocol: TCP
      port: 8429
      targetPort: 8429
  type: ClusterIP
