apiVersion: v1
kind: Service
metadata:
  name: {{ include "vmagent.fullname" . }}
spec:
  selector:
    app: {{ include "vmagent.name" . }}
  ports:
    - protocol: TCP
      port: 8429
      targetPort: 8429
  type: ClusterIP